---
- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true
  listen: reload systemd

- name: Restart studio
  ansible.builtin.systemd:
    name: studio
    state: restarted
  listen: restart studio

- name: Reload caddy
  ansible.builtin.systemd:
    name: caddy
    state: reloaded
  listen: reload caddy
