---
- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true
  listen: reload systemd

- name: Restart stuudio
  ansible.builtin.systemd:
    name: stuudio
    state: restarted
  listen: restart stuudio

- name: Reload caddy
  ansible.builtin.systemd:
    name: caddy
    state: reloaded
  listen: reload caddy
